package terminator.view.highlight;

import java.awt.event.*;

import terminator.view.*;

/**

@author Phil Norman
*/

public interface Highlighter {
	public String getName();
	
	/**
	 * Adds highlights to all lines of the view from the index given onwards.
	 */
	public void addHighlights(TerminalView view, int firstLineIndex);

	/** Invoked when the user clicks on a Highlight generated by this Highlighter. */
	public void highlightClicked(TerminalView view, Highlight highlight, String highlitText, MouseEvent event);
}
