package terminator.view.highlight;

import java.awt.event.*;

import terminator.view.*;

/**

@author Phil Norman
*/

public interface Highlighter {
	public String getName();
	
	/**
	 * Adds highlights to all lines of the view from the index given onwards.
	 * Returns the number of highlights added.
	 */
	public int addHighlights(JTextBuffer view, int firstLineIndex);

	/** Request to do something when the user clicks on a Highlight generated by this Highlighter. */
	public void highlightClicked(JTextBuffer view, Highlight highlight, String highlitText, MouseEvent event);
}
