.TH TERMINATOR "1" "" "jessies.org" "User Commands"
.SH NAME
terminator \- terminal emulator
.SH SYNOPSIS
.B terminator
[[\-n NAME] [\-\-working\-directory DIR] [COMMAND]]...
.SH DESCRIPTION
Each call to "terminator" creates a single window containing an arbitrary number of tabs.

X11-like
.B \-xrm
arguments are accepted but ignored for backwards compatibility.

XTerm-like
.B \-e
and
.B \-T
options are fully supported for backwards compatibility.
.SH EXAMPLES
This command (all one line) opens one new window containing two tabs called "console 1" and "console 2".
.nf
.sp
  terminator \-n "console 1" "telnet 192.168.32.32 2001" \\
             \-n "console 2" "telnet 192.168.32.32 2002" &
.sp
.fi
These two commands opens two new windows called "console 1" and "console 2".
.nf
.sp
  terminator \-n "console 1" "telnet 192.168.32.32 2001" &
  terminator \-n "console 2" "telnet 192.168.32.32 2002" &
.sp
.fi
Note the use of & to background the startup script. Don't use this if you want to wait for the terminal(s) to be closed.
.SH "SEE ALSO"
More documentation is available on our
.UR https://github.com/software-jessies-org/jessies/wiki/Terminator
github wiki
.UE
.SH "REPORTING BUGS"
Report bugs to <terminator-users@googlegroups.com>.
