.TH EDIT-AND-BLOCK "1" "" "" "User Commands"
.SH NAME
edit-and-block \- wait while a file is edited in Evergreen
.SH SYNOPSIS
edit-and-block FILE
.SH DESCRIPTION
A synonym for "evergreen --block FILE".
This is useful if you're asked for a blocking editor command and are unable to supply arguments.

(Arguably it would have been simpler to have evergreen(1) block by default but support a --no-block option, but that would have been unfortunate for interactive use.)
.SH "REPORTING BUGS"
Report bugs to <software@jessies.org>.
