#!/bin/sh

real_script=`readlink $0 || echo $0` # Deals with symbolic links to this script.

EDIT_CLASS_NAME=e.edit.Edit
EDIT_HOME=`dirname $real_script`
EDIT_HOME=`cd $EDIT_HOME ; pwd`  # Ensures we have an absolute path.
export EDIT_HOME
PATH=$PATH:$EDIT_HOME            # Make Edit's support tools available.
JAVA=java

# Enable Profiling.
#EXTRA_JAVA_OPTIONS+=-Xprof
# Enable Debugging.
#EXTRA_JAVA_OPTIONS+=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n

EDIT_PREFERENCES_DIRECTORY=$HOME/.$EDIT_CLASS_NAME

case "`uname`" in
Linux)
    EXTRA_CLASSPATH_ENTRIES=$EDIT_HOME/MRJ141Stubs.jar
    ;;
Darwin)
    # Darwin is what Mac OS X calls itself.
    EDIT_PREFERENCES_DIRECTORY=$HOME/Library/Preferences/$EDIT_CLASS_NAME
    PATH=/System/Library/Frameworks/JavaVM.framework/Commands:$PATH
    OS_SPECIFIC_OPTIONS=-Xdock:name=Edit:icon=$EDIT_HOME/edit.icns
    ;;
*)
    ;;
esac

if [ ! -d $EDIT_PREFERENCES_DIRECTORY ]; then
    echo "Edit: Couldn't find preferences directory '$EDIT_PREFERENCES_DIRECTORY'."
    echo "Edit: Creating preferences directory '$EDIT_PREFERENCES_DIRECTORY'."
    mkdir $EDIT_PREFERENCES_DIRECTORY
    echo "Edit: Copying default preferences."
    cp $EDIT_HOME/edit.properties-sample $EDIT_PREFERENCES_DIRECTORY/edit.properties
    echo "Edit: Away you go!"
fi

HEAP_SIZE=-Xmx1g

# Create a log file, and link to it as the newest.
EDIT_LOG=/tmp/edit.log.$$
# Symbolically linking to a file which doesn't exist is perfectly legal.
ln -s -f $EDIT_LOG /tmp/edit.log

JAVA_ENV=""
for VARIABLE in CVS_RSH DISPLAY EDIT_HOME HOME JAVA_HOME PATH
do
    eval VALUE="\${${VARIABLE}}"
    if [ "${VALUE}" != "" ]
    then
        JAVA_ENV="$JAVA_ENV -Denv.${VARIABLE}=${VALUE}"
    fi
done

$JAVA $OS_SPECIFIC_OPTIONS \
    $EXTRA_JAVA_OPTIONS \
    $HEAP_SIZE \
    -classpath $EDIT_HOME/classes:$EDIT_HOME/../salma-hayek/classes:$EXTRA_CLASSPATH_ENTRIES \
    $JAVA_ENV \
    -DpreferencesDirectory=$EDIT_PREFERENCES_DIRECTORY \
    $EDIT_CLASS_NAME \
>> $EDIT_LOG 2>&1 || cat $EDIT_LOG 1>&2 &
