# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = cdf05ed6-e1f8-11da-ae3f-00111123337e

# If we set this then it doesn't matter what the directory's called.
HUMAN_PROJECT_NAME = Evergreen

include ../salma-hayek/lib/build/simple.make
