#!/bin/bash
root="${@:-.}"
find $root \
    '(' -type d -name SCCS -prune ')' -or \
    '(' -type d -name BitKeeper -prune ')' -or \
    '(' -type d -name CVS -prune ')' -or \
    '(' -type d -name ppc_BOS_debug -prune ')' -or \
    '(' -type d -name ppc_BOS_release -prune ')' -or \
    '(' -type d -name ppc_BOS_profile -prune ')' -or \
    '(' -type d -name ppc_BOS-eabi_debug -prune ')' -or \
    '(' -type d -name ppc_BOS-eabi_release -prune ')' -or \
    '(' -type d -name ppc_BOS-eabi_profile -prune ')' -or \
    '(' -type d -name ix86_mingw32msvc_debug -prune ')' -or \
    '(' -type d -name ix86_mingw32msvc_release -prune ')' -or \
    '(' -type d -name ix86_mingw32msvc_profile -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.3_debug -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.3_release -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.3_profile -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.2_debug -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.2_release -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.2_profile -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.1_debug -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.1_release -prune ')' -or \
    '(' -type d -name ix86_linux_libc-2.1_profile -prune ')' -or \
    '(' -type d -name ix86_linux_debug -prune ')' -or \
    '(' -type d -name ix86_linux_release -prune ')' -or \
    '(' -type d -name ix86_linux_profile -prune ')' -or \
    '(' -type d -name billbox_BOS_debug -prune ')' -or \
    '(' -type d -name billbox_BOS_release -prune ')' -or \
    '(' -type d -name billbox_BOS_profile -prune ')' -or \
    '(' -type d -name ix86_solaris_debug -prune ')' -or \
    '(' -type d -name ix86_solaris_release -prune ')' -or \
    '(' -type d -name ix86_solaris_profile -prune ')' -or \
    '(' -type d -name sun4_solaris_debug -prune ')' -or \
    '(' -type d -name sun4_solaris_release -prune ')' -or \
    '(' -type d -name sun4_solaris_profile -prune ')' -or \
    -type f -print \
    | grep -v -e "\.bak$" -e "\.i$" -e "\.class$" -e "/err$" -e "~$" -e ".swp$" -e "\.o$" -e "\.gdb_history$" | sed -e 's/\(.*\)/"\1"/'
