#!/bin/bash

variant=`basename $0 | cut -c1`

usageText="Usage: ${variant}grep [--help] [<grep options>] [--] <search-term> <start-dir>*"
showHelp() {
    echo $usageText
    exit 0
}

grepOptions=""
nonOptions=()

while [ $# -gt 0 ]; do
    case "$1" in
    --help) shift ; showHelp ;;
    --)     shift ; break ;;
    -*)     grepOptions=$grepOptions" "$1 ; shift ;;
    *)      nonOptions[${#nonOptions[@]}]="$1" ; shift ;;
    esac
done
for i in "$@"
do
    nonOptions[${#nonOptions[@]}]="$i"
done

if [ ${#nonOptions[@]} -lt 1 ]; then
    showHelp
fi

searchTermSubscript=0
searchTerm=${nonOptions[$searchTermSubscript]}
unset nonOptions[$searchTermSubscript]

# If we have LANG set, grep takes a lot longer to start. And we're about to run it a lot of times.
unset LANG

grep=`type -p grep`
${variant}find "${nonOptions[@]}" | xargs $grep -nH $grepOptions "$searchTerm"
