#!/usr/bin/ruby -w
# Opens files in Edit.
# @author Elliott Hughes <enh@acm.org>

require 'pathname'
require 'net/telnet'

def previousViOnPath()
    directories = ENV["PATH"].split(':')
    executables = directories.map() {
        |directory|
        pathname = Pathname.new("#{directory}/vi")
        pathname.exist?() ? pathname.realpath().to_s() : nil
    }.compact().uniq()
    executables.delete($0)
    return executables[0]
end

def openFileOnLocalhost(filename)
    host = ENV["EDIT_HOME_SERVER"]
    if host == nil then
        host = 'localhost'
    end
    
    begin
        telnet = Net::Telnet.new('Host' => host, 'Port' => 1948, 'Telnetmode' => false)
        telnet.puts("open #{filename}\r")
        print(telnet.readlines().join("\n"))
        telnet.close()
    rescue
        system("#{previousViOnPath()} #{filename}")
    end
end

ARGV.each {
    | filename |
    openFileOnLocalhost(File.expand_path(filename))
}
