#!/usr/bin/ruby -w
ENV["PATH"]="/usr/local/bin:/opt/csw/bin:/opt/SUNWspro/bin:/usr/bin:/usr/sfw/bin:/usr/openwin/bin:/usr/ccs/bin"
# The previous line is quite specific to the particular host we're using and it may well be obsolete.

# A Subversion post-commit hook. Edit the configurable stuff below, and
# copy into your repository's hooks/ directory as "post-commit". Don't
# forget to "chmod a+x post-commit".

# You can test this script without checking in bogus revisions with, for example:
# umask 0002
# /home/software/svnroot/terminator/hooks/post-commit "" 1013

# ------------------------------------------------------------------------

# You *will* need to change these.

mail_domain="jessies.org" # Assumes all authors (and the to_address) share a domain.

to_address="software@#{mail_domain}"
reply_to_address=nil

if ENV["LOGNAME"] =~ /^(elliotth|martind)$/
  to_address=$1
end

# ------------------------------------------------------------------------

require 'cgi'
require 'pathname'

# __FILE__ may be relative to the current directory which we're about to change.
script_path=Pathname.new(__FILE__).realpath().dirname()
$: << script_path

# We can work out the repository name because we're <path>/<name>/hooks/post-commit
# We could also work this out from the spurious repository_path argument.
repository_path=Pathname.new(__FILE__).parent().parent()
repository_name=repository_path.basename()

require 'escaping.rb'
require 'patch-to-html-email.rb'

# Subversion's commit-email.pl suggests that svnlook might create files.
Dir.chdir("/tmp")

# What revision in what repository?
ARGV.shift() # throw away the spurious repository_path argument
rev = ARGV.shift()

# Get the overview information.
# svn(1) stores everything as UTF-8 but translates it on output according to LC_CTYPE.
# This appears not to be set by default on jessies.org in the environment in which this job runs.
ENV["LC_CTYPE"] = "en_US.UTF-8"
info=`svnlook info #{repository_path} -r #{rev}`
info_lines=info.split("\n")
author=info_lines.shift
date=info_lines.shift
info_lines.shift
comment=info_lines

# Remove the localized date that follows the ISO date.
date = date.gsub(/ \(.*\)$/, "")

from_address="#{author}@#{mail_domain}"

subject="#{repository_name} revision #{rev}"

body = ""

# Output the overview.
body << "<p class=\"revision-header\">#{date} / <b>#{author}</b></p>\n"
body << "<div class=\"check-in-comment\">\n"
body << "<p>"
comment.each() {
    |line|
    body << escapeTextLineToHtml(line)
}
body << "</p></div>\n"

# Get and output the patch.
# We'd like to | #{script_path}/bin/annotate-patch.rb
# But that requires that the correct version of the file is available as trunk/filename
changes=`svnlook diff #{repository_path} -r #{rev}`
changes.gsub!(/\r/, "") # In case we're running on MS Windows.

sendHtmlEmail(from_address, to_address, reply_to_address, subject, body, changes.split("\n"))

# Update the checked-out copy which, in salma-hayek, includes this post-commit trigger.

# FIXME: if there's a script error which prevents us from getting this far, it
# will require manual intervention to fix, because we'll be stuck at the broken
# revision forever.

updateResult=`{ cd #{script_path}/../#{repository_name} && svn update && make www-dist source-dist; } 2>&1`
if $? != 0
    begin
        # Consider using http://www.opengroup.org/onlinepubs/007908799/xcu/mailx.html if sendmail causes a problem.
        sendmail="/usr/sbin/sendmail"
        
        open("|#{sendmail} #{to_address}", "w") {
            |fd|
            fd.puts("To: #{to_address}")
            fd.puts("Subject: the post-commit update and dist failed")
            fd.puts("\n")
            fd.puts(updateResult)
        }
    rescue
        exit(1)
    end
end

# We're done.
exit(0)
