#!/usr/bin/ruby -w

# A Subversion post-commit hook. Edit the configurable stuff below, and
# copy into your repository's hooks/ directory as "post-commit". Don't
# forget to "chmod a+x post-commit".

# ------------------------------------------------------------------------

# You *will* need to change these.

address="software@jessies.org"
sendmail="/usr/sbin/sendmail"
svnlook="/opt/subversion-1.1.0-rc2/bin/svnlook"

if `whoami` =~ %r{^(martind)$}
  address=$1
  svnlook="svnlook"
end

# ------------------------------------------------------------------------

require 'cgi'
require 'pathname'

# __FILE__ may be relative to the current directory which we're about to change.
script_path=Pathname.new(__FILE__).realpath.dirname
$: << script_path

require 'escaping.rb'

# Subversion's commit-email.pl suggests that svnlook might create files.
Dir.chdir("/tmp")

# What revision in what repository?
repo = ARGV.shift()
rev = ARGV.shift()

# Get the overview information.
info=`#{svnlook} info #{repo} -r #{rev}`
info_lines=info.split("\n")
author=info_lines.shift
date=info_lines.shift
info_lines.shift
comment=info_lines

subject="#{repo} revision #{rev}"

body = "<html><head><title>#{subject}</title></head><body>"

# Output the overview.
body << "<p><b>#{author}</b> #{date}</p>"
body << "<p>"
comment.each() {
    |line|
    body << escapeTextLineToHtml(line)
}
body << "</p>"
body << "<hr noshade>"

# Get and output the patch.
changes=`#{svnlook} diff #{repo} -r #{rev}`
body << "<pre>"
changes.split("\n").each() {
    |line|
    color = "black"
    if line =~ /^Modified: / || line =~ /^=+$/ || line =~ /^@@ /
        color = "gray"
    elsif line =~ /^-/
        color = "red"
    elsif line =~ /^\+/
        color = "blue"
    end
    body << "<font color=\"#{color}\">#{CGI.escapeHTML(line)}</font>\n"
}
body << "</pre>"
body << "</body></html>"

# Write the header.
header = ""
header << "To: #{address}\n"
header << "From: #{address}\n"
header << "Subject: #{subject}\n"
header << "Reply-to: #{address}\n"
header << "MIME-Version: 1.0\n"
header << "Content-Type: text/html; charset=UTF-8\n"
header << "Content-Transfer-Encoding: 8bit\n"
header << "\n"

# Send the mail.
begin
    fd = open("|#{sendmail} #{address}", "w")
    fd.print(header)
    fd.print(body)
rescue
    exit(1)
end
fd.close

# Keep the post-commit trigger up-to-date.
Dir.chdir(script_path)
system("svn update")

# We're done.
exit(0)
