/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class terminator_terminal_PtyProcess */

#ifndef _Included_terminator_terminal_PtyProcess
#define _Included_terminator_terminal_PtyProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     terminator_terminal_PtyProcess
 * Method:    startProcess
 * Signature: (Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/FileDescriptor;)I
 */
JNIEXPORT jint JNICALL Java_terminator_terminal_PtyProcess_startProcess
  (JNIEnv *, jobject, jobjectArray, jobject, jobject);

/*
 * Class:     terminator_terminal_PtyProcess
 * Method:    sendResizeNotification
 * Signature: (Ljava/awt/Dimension;Ljava/awt/Dimension;)V
 */
JNIEXPORT void JNICALL Java_terminator_terminal_PtyProcess_sendResizeNotification
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     terminator_terminal_PtyProcess
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_terminator_terminal_PtyProcess_destroy
  (JNIEnv *, jobject);

/*
 * Class:     terminator_terminal_PtyProcess
 * Method:    waitFor
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_terminator_terminal_PtyProcess_waitFor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
