# This must always remain the same for the Windows installer infrastructure
# to know which program to upgrade.
UPGRADE_GUID = 9034247d-d2c9-e511-9464-00059a3c7a00

include ../salma-hayek/lib/build/simple.make
