#!/bin/sh

classes_jar_file=`locate /rt.jar | head -1`
if [ `uname` == "Darwin" ];
then
    classes_jar_file=/System/Library/Frameworks/JavaVM.framework/Classes/classes.jar
fi
export CLASSPATH=$classes_jar_file:classes

find classes -name '*.class'|xargs rm -f
find src -name '*.java'|xargs jikes -cp $CLASSPATH -d classes +D +P +Pall +Pno-serial +Pno-redundant-modifiers

