#!/bin/bash
TERMINATOR_HOME=`dirname $0`
PTY_BINARY=$TERMINATOR_HOME/pty/pty-`uname`-`arch`
CLASSPATH=$TERMINATOR_HOME/terminator.jar

mkdir -p ~/.terminal-logs && chmod og-rx ~/.terminal-logs

# If we don't have a pre-compiled 'pty' program for this
# architecture, try to build it.
test -e $PTY_BINARY || make -C pty/

exec java -cp $CLASSPATH -Dpty.binary=$PTY_BINARY terminatorn.Terminator "$@"
