#!/bin/bash
TERMINATOR_HOME=`dirname $0`
CLASSPATH=$TERMINATOR_HOME/classes:$TERMINATOR_HOME/../salma-hayek/classes
PTY_BINARY=$TERMINATOR_HOME/pty/pty-`uname`-`arch`

mkdir -p ~/.terminal-logs && chmod og-rx ~/.terminal-logs

# If we don't have a pre-compiled 'pty' program for this
# architecture, try to build it.
test -e $PTY_BINARY || make -C pty/

case "`uname`" in
Darwin)
    OS_SPECIFIC_OPTIONS=-Xdock:name=Terminator:icon=/Applications/Utilities/Terminal.app/Contents/Resources/icon.icns
    ;;
*)
    ;;
esac

exec java -cp $CLASSPATH $OS_SPECIFIC_OPTIONS -Dpty.binary=$PTY_BINARY terminatorn.Terminator "$@"
